Lesson2
Egor-oop/geekshop1 pull request #2
Opened 2021-08-16 14:59 UTC by Egor-oop

2021-08-16 14:59 UTC, Egor-oop commented
Нет css в продуктс

2021-08-16 14:59 UTC, Egor-oop commented
Помогите

2021-08-17 12:19 UTC, Vokler commented
Опишите подробнее проблему.
Так же учтите замечания, которые я вам оставил к 1ому ДЗ и исправьте тут

2021-08-17 13:01 UTC, Egor-oop commented
@Vokler У меня не работает .gitignore название у меня правильное, но что то не так.

Про CSS на странице Products. У меня оно не отображается.

2021-08-17 13:57 UTC, Egor-oop commented
не видит

2021-08-18 11:33 UTC, Vokler requested changes
.gitignore у вас работает, просто видимо вы сначала запушили код в репозиторий, а потом уже добавили файлы в gitignore.
Чтобы убрать файлы, вот по шагам что нужно сделать:
Алгоритм удаления каталога/файла из репозитория:
1. Удаляете из .gitignore файлы, которые игнорируются (потому что git вообще их не видит и даже, если вы удаляете эти файл из проекта, git продолжает игнорировать любые действия с этими фалами);
2. Удаляете сами файлы из проекта;
3. Делаете git push;
4. Обратно возвращаете в .gitignore файлы, которые нужно игнорировать;
5. Делаете git push

2021-08-18 11:33 UTC, Vokler commented on products/templates/products/index.html
> +    <link href="static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
Перед `static` должен быть слэш, то есть вот так:
`<link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">`

Но вообще во 2ом ДЗ нужно подключить статику загрузкой через шаблонный тег `{% load static %}`, как мы это делали на уроке

2021-08-19 10:49 UTC, Vokler commented
У вас все равно по-прежнему имеются файлы в проекте `db.sqlite3` и `.idea`.

Так же у вас появились конфликты (это когда код в отпачкованной ветке конфликтует с главной веткой) между двумя ветками. Чтобы решить данную проблему:
1. В текущей ветке сделайте git pull master ветки
2. А потом сделайте git push

2021-08-19 17:02 UTC, Egor-oop commented
Готово

2021-08-20 08:27 UTC, Vokler commented
Все осталось по-прежнему

2021-08-23 09:25 UTC, merged