Problems with login
Egor-oop/geekshop1 pull request #4
Opened 2021-08-28 09:42 UTC by Egor-oop

Когда я пытаюсь войти в своего пользователя на станице users/login/. То у меня показывает что в поле для имени у меня просит почту.
*Надеюсь хоть как-то объяснил*

2021-08-28 09:43 UTC, Egor-oop commented
@Vokler

2021-08-31 08:15 UTC, Egor-oop commented
Update:
Я поменял там чтобы было поле не с email а с userName. Вы можете наблюдать это в последнем коммите.
Выводится ошибка ```html
<ul class="errorlist"><li>username<ul class="errorlist"><li>This field is required.</li></ul></li><li>password<ul class="errorlist"><li>This field is required.</li></ul></li></ul>
```

2021-08-31 15:25 UTC, Vokler requested changes

2021-08-31 15:25 UTC, Vokler commented on users/templates/users/login.html
> +                                        <input class="form-control py-4" id="inputUsername" type="text"
Так у вас не срабатывает, потому что вы поля формы тут не передаете.
Посмотрите внимательнее, как мы это делали на уроке.
Тут должно быть вместо тега input - `{{ form.username }}`

2021-08-31 17:59 UTC, Egor-oop commented on users/templates/users/login.html
> +                                        <input class="form-control py-4" id="inputUsername" type="text"
Thanks

2021-08-31 18:19 UTC, Egor-oop commented
У меня не отображаются инпуты. Не понимаю почему их нет

2021-09-01 07:50 UTC, Egor-oop commented
@Vokler

2021-09-01 17:01 UTC, Vokler commented
А как у вас? Вы имеете в виду, что не срабатывает `{{ form.username}}`?
Приложите скриншот

2021-09-01 17:57 UTC, Egor-oop commented
> А как у вас? Вы имеете в виду, что не срабатывает `{{ form.username}}`?
> Приложите скриншот

![Снимок экрана (221)](https://user-images.githubusercontent.com/72152812/131720383-3d2d65d3-735a-4b40-b050-0d172ca0745c.png)

2021-09-01 18:14 UTC, Egor-oop commented
@Vokler извините что вас тревожу так часто просто мне срочно. А то сильно отстаю.

2021-09-02 08:16 UTC, Vokler requested changes

2021-09-02 08:16 UTC, vprinz commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
Так у вас форма регистрации и не будет отображаться. Контекст же пустой, тут нужно передавать форму, как это в login() контроллере

2021-09-02 10:51 UTC, Egor-oop commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
теперь так 
![Снимок экрана (222)](https://user-images.githubusercontent.com/72152812/131831271-b0fcda5b-0504-4c21-ab99-db850301c6aa.png)

2021-09-02 11:01 UTC, Egor-oop commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
@Vokler

2021-09-02 11:33 UTC, Vokler commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
Вы пушьте изменения в репозиторий, чтобы я видел, что вы меняете

2021-09-02 13:10 UTC, Egor-oop commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
Запушил

2021-09-02 13:11 UTC, Egor-oop commented on users/views.py
> +        'title': 'Geekshop - Регистрация'
@Vokler

2021-09-02 15:51 UTC, Vokler requested changes

2021-09-02 15:51 UTC, Vokler commented on users/views.py
> +        form = UserLoginForm(data=request.POST)
Пересмотрите внимательнее 4ый урок. Почему вы используете форму для авторизации в регистрации?

2021-09-02 16:00 UTC, Egor-oop commented on users/views.py
> +        form = UserLoginForm(data=request.POST)
Я это исправил но не все поля отображаются 
![Снимок экрана (223)](https://user-images.githubusercontent.com/72152812/131877577-67b604b5-11dd-4223-93bf-e41b446cebe7.png)

2021-09-02 16:01 UTC, Egor-oop commented on users/views.py
> +        form = UserLoginForm(data=request.POST)
А не всё ок

2021-09-03 04:57 UTC, Egor-oop commented
@Vokler сделаете merge

2021-09-03 08:21 UTC, Vokler approved these changes

2021-09-03 08:21 UTC, merged

2026-01-28 12:53 UTC, Egor-oop commented
@vprinz , Как дела?