Lesson8
Egor-oop/geekshop1 pull request #9
Opened 2021-09-13 15:35 UTC by Egor-oop

2021-09-13 15:35 UTC, Egor-oop commented
У меня ошибка. Помогите мне @Vokler

2021-09-13 15:36 UTC, Egor-oop commented
- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] 

- [ ] ggg

- [ ] fff

- [ ] sss

2021-09-14 05:35 UTC, Egor-oop commented
@Vokler

2021-09-14 14:12 UTC, Vokler requested changes

2021-09-14 14:12 UTC, Vokler commented on products/templates/products/products.html
> +                <a href="{% url 'products:category' category_id %}">
А category_id откуда берется? В context вы такой параметр не передавали.
Тут нужен цикл и передавать потом `category.id`, обращаясь к атрибуту `id` объекта `category`

2021-09-15 09:25 UTC, Vokler commented
Все готово? Можно мержить?

2021-09-15 09:26 UTC, Egor-oop commented
> Все готово? Можно мержить?

щас баг исправлю и закомитчу

2021-09-15 09:31 UTC, Egor-oop commented
@Vokler мержите

2021-09-16 07:33 UTC, merged